### PR TITLE
Fixed possible test failure on date/time rollover

### LINKED ISSUE #6: Fix date dependency in unit tests

### PR DESCRIPTION
**Pull request by brettminnie**
Closes #6

### CODE REVIEW

File: src/TransformCore/PHE/LocalHealthAuthorityBundle/Tests/Service/DistrictCouncilServiceTest.php [hunk 1]
```diff
@@ -98,6 +103,7 @@ protected function mockEntityManager()
 
     public function setUp()
```
Comment (eddiejaoude) [inline src/TransformCore/PHE/LocalHealthAuthorityBundle/Tests/Service/DistrictCouncilServiceTest.php]: Easier to read if the setup is at the top of the file - but not a major issue
